
spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:password00000@cluster0.d0qi4xw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  servlet:
    context-path: /journal