
spring:
  data:
    mongodb:
      uri: mongodb+srv:
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  servlet:

    context-path: /journal
